# Form implementation generated from reading ui file '.\form.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import src.res_rc

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(580, 391)
        Widget.setMinimumSize(QtCore.QSize(580, 391))
        Widget.setMaximumSize(QtCore.QSize(580, 391))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        Widget.setFont(font)
        Widget.setMouseTracking(True)
        Widget.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.help_but = QtWidgets.QPushButton(parent=Widget)
        self.help_but.setGeometry(QtCore.QRect(30, 220, 51, 51))
        self.help_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.help_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"    font: 700  \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"")
        self.help_but.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/document.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.help_but.setIcon(icon)
        self.help_but.setIconSize(QtCore.QSize(20, 20))
        self.help_but.setObjectName("help_but")
        self.info_but = QtWidgets.QPushButton(parent=Widget)
        self.info_but.setGeometry(QtCore.QRect(30, 310, 51, 51))
        self.info_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.info_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"    font: 700  \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"")
        self.info_but.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/interrogation.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.info_but.setIcon(icon1)
        self.info_but.setIconSize(QtCore.QSize(18, 18))
        self.info_but.setObjectName("info_but")
        self.label = QtWidgets.QLabel(parent=Widget)
        self.label.setGeometry(QtCore.QRect(10, 40, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/res/openmodelica.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Widget)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 121, 41))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #333333;           /* Dark gray for text */\n"
"    font-size: 17px;          /* Large font for emphasis */\n"
"    font-weight: bold;        /* Bold text for prominence */\n"
"    background: none;         /* Transparent background */\n"
"    padding: 5px 10px;        /* Add padding for spacing */\n"
"    border: none;   \n"
"    text-align: center;       /* Centered text */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.set_but = QtWidgets.QPushButton(parent=Widget)
        self.set_but.setGeometry(QtCore.QRect(400, 180, 101, 51))
        self.set_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.set_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"    font: 700  \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2F2F2;\n"
"    color: #A9A9A9; \n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/time-fast.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.set_but.setIcon(icon2)
        self.set_but.setObjectName("set_but")
        self.main_label = QtWidgets.QLabel(parent=Widget)
        self.main_label.setGeometry(QtCore.QRect(150, 30, 341, 41))
        self.main_label.setStyleSheet("font: 8pt \"Poppins\";")
        self.main_label.setObjectName("main_label")
        self.clear_but = QtWidgets.QPushButton(parent=Widget)
        self.clear_but.setGeometry(QtCore.QRect(510, 30, 41, 41))
        self.clear_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clear_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"    font: 700  \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2F2F2;\n"
"    color: #A9A9A9; \n"
"}\n"
"")
        self.clear_but.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/clear-alt.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clear_but.setIcon(icon3)
        self.clear_but.setObjectName("clear_but")
        self.groupBox = QtWidgets.QGroupBox(parent=Widget)
        self.groupBox.setGeometry(QtCore.QRect(130, 170, 241, 191))
        self.groupBox.setStyleSheet("font: 11pt \"Product Sans\";")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setStyleSheet("font: 10pt \"Product Sans\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.start_line = QtWidgets.QLineEdit(parent=self.groupBox)
        self.start_line.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;  /* Light gray background for input fields */\n"
"    color: #333333;            /* Dark gray text for readability */\n"
"    border: 1px solid #D3D3D3; /* Subtle border */\n"
"    border-radius: 6px;        /* Rounded corners */\n"
"    padding: 6px 8px;          /* Add padding for comfortable input */\n"
"    font-size: 13px;   \n"
"    font:  \"Product Sans\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4; /* Blue border when focused */\n"
"    background-color: #FFFFFF; /* Pure white background on focus */\n"
"    outline: none;             /* Removes the default focus glow */\n"
"}\n"
"")
        self.start_line.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhTime)
        self.start_line.setText("")
        self.start_line.setClearButtonEnabled(True)
        self.start_line.setObjectName("start_line")
        self.verticalLayout.addWidget(self.start_line)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setStyleSheet("font: 10pt \"Product Sans\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.stop_line = QtWidgets.QLineEdit(parent=self.groupBox)
        self.stop_line.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;  /* Light gray background for input fields */\n"
"    color: #333333;            /* Dark gray text for readability */\n"
"    border: 1px solid #D3D3D3; /* Subtle border */\n"
"    border-radius: 6px;        /* Rounded corners */\n"
"    padding: 6px 8px;          /* Add padding for comfortable input */\n"
"    font-size: 13px;   \n"
"    font:  \"Product Sans\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4; /* Blue border when focused */\n"
"    background-color: #FFFFFF; /* Pure white background on focus */\n"
"    outline: none;             /* Removes the default focus glow */\n"
"}\n"
"")
        self.stop_line.setClearButtonEnabled(True)
        self.stop_line.setObjectName("stop_line")
        self.verticalLayout.addWidget(self.stop_line)
        self.folder_but = QtWidgets.QPushButton(parent=Widget)
        self.folder_but.setGeometry(QtCore.QRect(140, 90, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setBold(False)
        font.setItalic(False)
        self.folder_but.setFont(font)
        self.folder_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.folder_but.setStyleSheet("QPushButton {\n"
"    background-color: #0078D4;\n"
"    color: white; \n"
"    border: none;  \n"
"    border-radius: 6px;    \n"
"    font-size: 14px;  \n"
"    font-weight: bold;     \n"
"    font: \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005A9E; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003E73; \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    color: white;   \n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/folder-open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.folder_but.setIcon(icon4)
        self.folder_but.setIconSize(QtCore.QSize(22, 22))
        self.folder_but.setObjectName("folder_but")
        self.launch_but = QtWidgets.QPushButton(parent=Widget)
        self.launch_but.setGeometry(QtCore.QRect(390, 90, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Product Sans")
        font.setBold(False)
        font.setItalic(False)
        self.launch_but.setFont(font)
        self.launch_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.launch_but.setStyleSheet("QPushButton {\n"
"    background-color: #28A745; \n"
"    color: white;         \n"
"    border: none;            \n"
"    border-radius: 6px; \n"
"    font-size: 14px;        \n"
"    font-weight: bold;   \n"
"    font:   \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E7E34; \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9; \n"
"    color: white;         \n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/rocket-hand.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.launch_but.setIcon(icon5)
        self.launch_but.setIconSize(QtCore.QSize(22, 22))
        self.launch_but.setObjectName("launch_but")
        self.clear_time_but = QtWidgets.QPushButton(parent=Widget)
        self.clear_time_but.setGeometry(QtCore.QRect(400, 240, 101, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.clear_time_but.setFont(font)
        self.clear_time_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clear_time_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"    font: 700  \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2F2F2;\n"
"    color: #A9A9A9; \n"
"}\n"
"")
        self.clear_time_but.setIcon(icon3)
        self.clear_time_but.setObjectName("clear_time_but")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Widget)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 300, 131, 61))
        self.groupBox_2.setStyleSheet("font: 11pt \"Product Sans\";")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mat_check_but = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.mat_check_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.mat_check_but.setObjectName("mat_check_but")
        self.verticalLayout_2.addWidget(self.mat_check_but)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.help_but.setToolTip(_translate("Widget", "<html><head/><body><p>Documentation</p></body></html>"))
        self.info_but.setToolTip(_translate("Widget", "<html><head/><body><p>Information</p></body></html>"))
        self.info_but.setWhatsThis(_translate("Widget", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Widget", "<html><head/><body><p><span style=\" font-style:italic; color:#000000;\">LAUNCHER</span></p></body></html>"))
        self.set_but.setText(_translate("Widget", "  Set Time"))
        self.main_label.setText(_translate("Widget", "Model : no model selected"))
        self.clear_but.setToolTip(_translate("Widget", "<html><head/><body><p>clear</p></body></html>"))
        self.groupBox.setTitle(_translate("Widget", "Simulation Settings"))
        self.label_3.setText(_translate("Widget", "Start time:"))
        self.start_line.setPlaceholderText(_translate("Widget", "Enter start time in seconds"))
        self.label_4.setText(_translate("Widget", "Stop time:"))
        self.stop_line.setPlaceholderText(_translate("Widget", "Enter stop time in seconds"))
        self.folder_but.setText(_translate("Widget", "  Choose Model"))
        self.launch_but.setText(_translate("Widget", "  Launch Model"))
        self.clear_time_but.setText(_translate("Widget", "  Clear Time"))
        self.groupBox_2.setTitle(_translate("Widget", " Output format"))
        self.mat_check_but.setText(_translate("Widget", ".mat"))
