# Form implementation generated from reading ui file '.\newgui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import src.res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(631, 400))
        MainWindow.setMaximumSize(QtCore.QSize(631, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.menu_widget.setGeometry(QtCore.QRect(9, 9, 111, 374))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_widget.sizePolicy().hasHeightForWidth())
        self.menu_widget.setSizePolicy(sizePolicy)
        self.menu_widget.setObjectName("menu_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.home_but = QtWidgets.QPushButton(parent=self.menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_but.sizePolicy().hasHeightForWidth())
        self.home_but.setSizePolicy(sizePolicy)
        self.home_but.setMinimumSize(QtCore.QSize(109, 48))
        self.home_but.setMaximumSize(QtCore.QSize(109, 48))
        self.home_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home_but.setMouseTracking(True)
        self.home_but.setStyleSheet("QPushButton {\n"
"    font: 600 9pt \"Montserrat\";\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.home_but.setIcon(icon)
        self.home_but.setObjectName("home_but")
        self.verticalLayout.addWidget(self.home_but)
        self.theme_but = QtWidgets.QPushButton(parent=self.menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theme_but.sizePolicy().hasHeightForWidth())
        self.theme_but.setSizePolicy(sizePolicy)
        self.theme_but.setMinimumSize(QtCore.QSize(109, 47))
        self.theme_but.setMaximumSize(QtCore.QSize(109, 47))
        self.theme_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.theme_but.setStyleSheet("QPushButton {\n"
"    font: 600 9pt \"Montserrat\";\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/customize-edit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.theme_but.setIcon(icon1)
        self.theme_but.setObjectName("theme_but")
        self.verticalLayout.addWidget(self.theme_but)
        self.history_but = QtWidgets.QPushButton(parent=self.menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_but.sizePolicy().hasHeightForWidth())
        self.history_but.setSizePolicy(sizePolicy)
        self.history_but.setMinimumSize(QtCore.QSize(109, 48))
        self.history_but.setMaximumSize(QtCore.QSize(109, 48))
        self.history_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.history_but.setStyleSheet("QPushButton {\n"
"    font: 600 9pt \"Montserrat\";\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/file-circle-info.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.history_but.setIcon(icon2)
        self.history_but.setObjectName("history_but")
        self.verticalLayout.addWidget(self.history_but)
        self.doc_but = QtWidgets.QPushButton(parent=self.menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doc_but.sizePolicy().hasHeightForWidth())
        self.doc_but.setSizePolicy(sizePolicy)
        self.doc_but.setMinimumSize(QtCore.QSize(109, 47))
        self.doc_but.setMaximumSize(QtCore.QSize(109, 47))
        self.doc_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.doc_but.setStyleSheet("QPushButton {\n"
"    font: 600 9pt \"Montserrat\";\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/document.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.doc_but.setIcon(icon3)
        self.doc_but.setObjectName("doc_but")
        self.verticalLayout.addWidget(self.doc_but)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.menu_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(109, 49))
        self.pushButton_5.setMaximumSize(QtCore.QSize(90, 50))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    font: 600 9pt \"Montserrat\";\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/exit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.main_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(126, 9, 516, 377))
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(507, 450))
        self.stackedWidget.setMaximumSize(QtCore.QSize(507, 461))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget_8 = QtWidgets.QWidget(parent=self.page)
        self.widget_8.setGeometry(QtCore.QRect(9, 9, 522, 357))
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_2.setMinimumSize(QtCore.QSize(480, 59))
        self.widget_2.setMaximumSize(QtCore.QSize(480, 59))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.folder_but = QtWidgets.QPushButton(parent=self.widget_2)
        self.folder_but.setMinimumSize(QtCore.QSize(161, 41))
        self.folder_but.setMaximumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        font.setItalic(False)
        self.folder_but.setFont(font)
        self.folder_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.folder_but.setStyleSheet("QPushButton {\n"
"    background-color: #0078D4;\n"
"    color: white; \n"
"    border: none;  \n"
"    border-radius: 6px;    \n"
"    font-size: 14px;  \n"
"    font: 600 9pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005A9E; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003E73; \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    color: white;   \n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/folder-open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.folder_but.setIcon(icon5)
        self.folder_but.setIconSize(QtCore.QSize(22, 22))
        self.folder_but.setObjectName("folder_but")
        self.horizontalLayout_3.addWidget(self.folder_but)
        spacerItem4 = QtWidgets.QSpacerItem(100, 40, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.launch_but = QtWidgets.QPushButton(parent=self.widget_2)
        self.launch_but.setMinimumSize(QtCore.QSize(161, 0))
        self.launch_but.setMaximumSize(QtCore.QSize(161, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        font.setItalic(False)
        self.launch_but.setFont(font)
        self.launch_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.launch_but.setStyleSheet("QPushButton {\n"
"    background-color: #28A745; \n"
"    color: white;         \n"
"    border: none;            \n"
"    border-radius: 6px; \n"
"    font-size: 14px;   \n"
"    font: 600 9pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E7E34; \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9; \n"
"    color: white;         \n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/rocket-hand.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.launch_but.setIcon(icon6)
        self.launch_but.setIconSize(QtCore.QSize(22, 22))
        self.launch_but.setObjectName("launch_but")
        self.horizontalLayout_3.addWidget(self.launch_but)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_5 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(parent=self.widget_5)
        self.groupBox.setMinimumSize(QtCore.QSize(201, 181))
        self.groupBox.setMaximumSize(QtCore.QSize(201, 181))
        self.groupBox.setStyleSheet("font: 600 10pt \"Montserrat\";")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setStyleSheet("font:  500 9pt \"Montserrat\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.start_line = QtWidgets.QLineEdit(parent=self.groupBox)
        self.start_line.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;  /* Light gray background for input fields */\n"
"    color: #333333;            /* Dark gray text for readability */\n"
"    border: 1px solid #D3D3D3; /* Subtle border */\n"
"    border-radius: 6px;        /* Rounded corners */\n"
"    padding: 6px 8px;          /* Add padding for comfortable input */\n"
"    font-size: 13px;   \n"
"    font:  \"Product Sans\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4; /* Blue border when focused */\n"
"    background-color: #FFFFFF; /* Pure white background on focus */\n"
"    outline: none;             /* Removes the default focus glow */\n"
"}\n"
"")
        self.start_line.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhTime)
        self.start_line.setText("")
        self.start_line.setClearButtonEnabled(True)
        self.start_line.setObjectName("start_line")
        self.verticalLayout_6.addWidget(self.start_line)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setStyleSheet("font: 500 9pt \"Montserrat\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.stop_line = QtWidgets.QLineEdit(parent=self.groupBox)
        self.stop_line.setStyleSheet("QLineEdit {\n"
"    background-color: #F5F5F5;  /* Light gray background for input fields */\n"
"    color: #333333;            /* Dark gray text for readability */\n"
"    border: 1px solid #D3D3D3; /* Subtle border */\n"
"    border-radius: 6px;        /* Rounded corners */\n"
"    padding: 6px 8px;          /* Add padding for comfortable input */\n"
"    font-size: 13px;   \n"
"    font:  \"Product Sans\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4; /* Blue border when focused */\n"
"    background-color: #FFFFFF; /* Pure white background on focus */\n"
"    outline: none;             /* Removes the default focus glow */\n"
"}\n"
"")
        self.stop_line.setClearButtonEnabled(True)
        self.stop_line.setObjectName("stop_line")
        self.verticalLayout_6.addWidget(self.stop_line)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.widget_5)
        spacerItem6 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.widget_6)
        self.groupBox_2.setMinimumSize(QtCore.QSize(131, 61))
        self.groupBox_2.setMaximumSize(QtCore.QSize(131, 61))
        self.groupBox_2.setStyleSheet("font: 600 9pt \"Montserrat\";\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plot_check_but = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.plot_check_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.plot_check_but.setStyleSheet("font: 600 9pt \"Montserrat\";")
        self.plot_check_but.setObjectName("plot_check_but")
        self.verticalLayout_4.addWidget(self.plot_check_but)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.set_but = QtWidgets.QPushButton(parent=self.widget_6)
        self.set_but.setMinimumSize(QtCore.QSize(131, 51))
        self.set_but.setMaximumSize(QtCore.QSize(131, 51))
        self.set_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.set_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font: 600 9pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2F2F2;\n"
"    color: #A9A9A9; \n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/time-fast.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.set_but.setIcon(icon7)
        self.set_but.setObjectName("set_but")
        self.verticalLayout_5.addWidget(self.set_but)
        self.clear_time_but = QtWidgets.QPushButton(parent=self.widget_6)
        self.clear_time_but.setMinimumSize(QtCore.QSize(131, 51))
        self.clear_time_but.setMaximumSize(QtCore.QSize(131, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(9)
        font.setItalic(False)
        self.clear_time_but.setFont(font)
        self.clear_time_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clear_time_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font: 600 9pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2F2F2;\n"
"    color: #A9A9A9; \n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/res/ui_icons/clear-alt.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.clear_time_but.setIcon(icon8)
        self.clear_time_but.setObjectName("clear_time_but")
        self.verticalLayout_5.addWidget(self.clear_time_but)
        self.horizontalLayout.addWidget(self.widget_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout_2.addWidget(self.widget_7, 2, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.widget_8)
        self.widget.setMinimumSize(QtCore.QSize(471, 51))
        self.widget.setMaximumSize(QtCore.QSize(471, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_label = QtWidgets.QLabel(parent=self.widget)
        self.main_label.setMinimumSize(QtCore.QSize(310, 41))
        self.main_label.setMaximumSize(QtCore.QSize(341, 41))
        self.main_label.setStyleSheet("font:  9pt \"Montserrat\";")
        self.main_label.setObjectName("main_label")
        self.horizontalLayout_2.addWidget(self.main_label)
        self.clear_but = QtWidgets.QPushButton(parent=self.widget)
        self.clear_but.setMinimumSize(QtCore.QSize(41, 41))
        self.clear_but.setMaximumSize(QtCore.QSize(41, 41))
        self.clear_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clear_but.setStyleSheet("QPushButton {\n"
"    background-color: #EAEAEA; \n"
"    color: #333333;  \n"
"    border: 1px solid #D3D3D3; \n"
"    border-radius: 6px;\n"
"    font-size: 13px;      \n"
"    font: 700  \"Product Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D6D6D6;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #F2F2F2;\n"
"    color: #A9A9A9; \n"
"}\n"
"")
        self.clear_but.setText("")
        self.clear_but.setIcon(icon8)
        self.clear_but.setObjectName("clear_but")
        self.horizontalLayout_2.addWidget(self.clear_but)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(parent=self.page)
        self.status_label.setGeometry(QtCore.QRect(100, 360, 251, 16))
        self.status_label.setStyleSheet("font:  9pt \"Montserrat\";")
        self.status_label.setObjectName("status_label")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(parent=self.page_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.label.setStyleSheet("font: 800 14pt \"Montserrat\";")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(140, 90, 171, 41))
        self.comboBox.setStyleSheet("font:  9pt \"Montserrat\";")
        self.comboBox.setObjectName("comboBox")
        self.theme_set_but = QtWidgets.QPushButton(parent=self.page_2)
        self.theme_set_but.setGeometry(QtCore.QRect(170, 150, 121, 41))
        self.theme_set_but.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.theme_set_but.setStyleSheet("QPushButton {\n"
"    background-color: #0078D4;\n"
"    color: white; \n"
"    border: none;  \n"
"    border-radius: 6px;    \n"
"    font-size: 14px;  \n"
"    font: 600 9pt \"Montserrat\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005A9E; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003E73; \n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A9A9A9;\n"
"    color: white;   \n"
"}\n"
"")
        self.theme_set_but.setObjectName("theme_set_but")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_7 = QtWidgets.QLabel(parent=self.page_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.label_7.setStyleSheet("font: 800 14pt \"Montserrat\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.listWidget = QtWidgets.QListWidget(parent=self.page_3)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 461, 311))
        self.listWidget.setStyleSheet("font:  9pt \"Montserrat\";")
        self.listWidget.setObjectName("listWidget")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(parent=self.page_4)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 181, 51))
        self.label_4.setStyleSheet("font: 800 14pt \"Montserrat\";")
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(parent=self.page_4)
        self.label_11.setGeometry(QtCore.QRect(30, 220, 481, 51))
        self.label_11.setStyleSheet("font: 10pt \"Montserrat\";")
        self.label_11.setOpenExternalLinks(True)
        self.label_11.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(parent=self.page_4)
        self.label_10.setGeometry(QtCore.QRect(110, 20, 221, 211))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/icons/res/pngs/OML_NBG.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(True)
        self.label_10.setOpenExternalLinks(False)
        self.label_10.setObjectName("label_10")
        self.label_13 = QtWidgets.QLabel(parent=self.page_4)
        self.label_13.setGeometry(QtCore.QRect(20, 290, 341, 61))
        self.label_13.setStyleSheet("font: 800 14pt \"Montserrat\";\n"
"\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.page_4)
        self.label_14.setGeometry(QtCore.QRect(30, 350, 151, 16))
        self.label_14.setStyleSheet("font: 10pt \"Montserrat\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.page_4)
        self.label_15.setGeometry(QtCore.QRect(180, 350, 61, 16))
        self.label_15.setStyleSheet("font: 10pt \"Montserrat\";")
        self.label_15.setOpenExternalLinks(True)
        self.label_15.setObjectName("label_15")
        self.label_2 = QtWidgets.QLabel(parent=self.page_4)
        self.label_2.setGeometry(QtCore.QRect(30, 280, 181, 16))
        self.label_2.setStyleSheet("font: 10pt \"Montserrat\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page_4)
        self.label_3.setGeometry(QtCore.QRect(210, 280, 151, 16))
        self.label_3.setStyleSheet("font: 10pt \"Montserrat\";\n"
"")
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.pushButton_5.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home_but.setText(_translate("MainWindow", "Home"))
        self.theme_but.setText(_translate("MainWindow", "Themes"))
        self.history_but.setText(_translate("MainWindow", "History"))
        self.doc_but.setText(_translate("MainWindow", "Docs"))
        self.pushButton_5.setText(_translate("MainWindow", "Exit"))
        self.folder_but.setText(_translate("MainWindow", "  Choose Model"))
        self.launch_but.setText(_translate("MainWindow", "  Launch Model"))
        self.groupBox.setTitle(_translate("MainWindow", "Simulation Settings"))
        self.label_5.setText(_translate("MainWindow", "Start time:"))
        self.start_line.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Product Sans\'; font-size:13px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.start_line.setPlaceholderText(_translate("MainWindow", "Enter start time in seconds"))
        self.label_6.setText(_translate("MainWindow", "Stop time:"))
        self.stop_line.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.stop_line.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.stop_line.setPlaceholderText(_translate("MainWindow", "Enter stop time in seconds"))
        self.plot_check_but.setText(_translate("MainWindow", " Plot the o/p"))
        self.set_but.setText(_translate("MainWindow", "  Set Time"))
        self.clear_time_but.setText(_translate("MainWindow", "  Clear Time"))
        self.main_label.setText(_translate("MainWindow", "Model : no model selected"))
        self.clear_but.setToolTip(_translate("MainWindow", "<html><head/><body><p>clear</p></body></html>"))
        self.status_label.setText(_translate("MainWindow", "Screening Task - OpenModelica GUI "))
        self.label.setText(_translate("MainWindow", "Themes"))
        self.theme_set_but.setText(_translate("MainWindow", "Set Theme"))
        self.label_7.setText(_translate("MainWindow", "History"))
        self.label_4.setText(_translate("MainWindow", "Documentation"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>For more information and usage instructions, please refer </p><p>to the official repository. <a href=\"https://github.com/mtm-x/OpenModelica-GUI\"><span style=\" text-decoration: underline; color:#005393;\">Click here</span></a></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Developed By"))
        self.label_14.setText(_translate("MainWindow", "Thamaraimanalan M "))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/mtm-x\"><span style=\" text-decoration: underline; color:#005393;\">GitHub</span></a></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "OpenModelica Official site -"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://openmodelica.org/\"><span style=\" text-decoration: underline; color:#005393;\">Click here</span></a></p></body></html>"))
